quckoo-org/api-tips-backend

- proto-gen.sh
- proto/test/v1/test.proto
- src/common/filters/RpcExceptionsFilter.ts
- src/common/interceptors/GrpcCorsInterceptor.ts
- src/main.ts
- src/modules/test/test.controller.ts
- src/modules/test/test.service.ts
> feat: exceptions

- .prettierrc
> upd - prettierrc

- proto/api_tips_access/v1/api_tips_access.proto
- src/ApiTips.Api/MapeerProfiles/Method/MethodProfile.cs
- src/ApiTips.Api/MapeerProfiles/Permission/PermissionProfile.cs
- src/ApiTips.Api/MapeerProfiles/Role/RoleProfile.cs
- src/ApiTips.Api/MapeerProfiles/User/UserProfile.cs
- src/ApiTips.Api/MapeerProfiles/User/UserResolverProfile.cs
- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsAccessService.cs
---
PR составлен по story/task - DP-440 / DP-1089
> feat: [DP-440]/[DP-1089] Имплементация методов access

- src/ApiTips.Api/Controllers/AuthController.cs
---
PR составлен по task - DP-1312
> feat: [DP-1312] Перевод сообщений ответа на английский язык и увеличение времени ожидания на восстановление пароля

- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsOrderService.cs
- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsTariffService.cs
---
PR составлен по story/task - DP-1303
> feat: [DP-1303] Перевод сообщений отправляемых на фронт

- src/ApiTips.Api/Migrations/20250204074409_init balance.Designer.cs
- src/ApiTips.Api/Migrations/20250204074409_init balance.cs
---
PR составлен по story/task - DP-454/DP-1357
> feat: [DP-1357] Миграция по балансу

- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsTariffService.cs
---
PR составлен по story/task - DP-1178/DP-1305
> feat: [DP-1305] Добавлены проверки дат периода действия тарифа

- src/ApiTips.Api/Controllers/AuthController.cs
- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsAccessService.cs
- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsInvoiceService.cs
> refactor: Переведены сообщения для отправки на английский язык

- proto/api_tips_order/v1/api_tips_order.proto
- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsOrderService.cs
---
PR составлен по story/task - DP-1236/DP-1400
> feat: [DP-1400] Добавлен фильтр заказов по почте пользователя

- proto/api_tips_access/v1/api_tips_access.proto
- src/ApiTips.Api/Extensions/Application/InjectionServiceCollection.cs
- src/ApiTips.Api/ServiceInterfaces/IUserService.cs
- src/ApiTips.Api/Services/Common/UserService.cs
- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsAccessService.cs
---
PR составлен по task - DP-1401
> feat: [DP-1401] Разработка метода для получения детальной информации для получения пользователя

- proto/api_tips_order/v1/api_tips_order.proto
- src/ApiTips.Api/Migrations/20250211111803_Edit order.Designer.cs
- src/ApiTips.Api/Migrations/20250211111803_Edit order.cs
- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsOrderService.cs
- src/ApiTips.Dal/schemas/data/Order.cs
---
PR составлен по story/task - DP-1236/DP-1399
> feat: [DP-1399] Добавлен токен доступа для заказов

- proto/api_tips_order/v1/api_tips_order.proto
- src/ApiTips.Api/MapperProfiles/Order/OrderProfile.cs
- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsOrderService.cs
---
PR составлен по story/task - DP-918/DP-1402
> feat: [DP-1402] Добавление метода для получения заказов для клиента

- proto/api_tips_access/v1/api_tips_access.proto
- proto/api_tips_order/v1/api_tips_order.proto
- src/ApiTips.Api/Controllers/AuthController.cs
- src/ApiTips.Api/MapperProfiles/User/UserProfile.cs
- src/ApiTips.Api/Migrations/20250219071204_MovedAccessTokenFromOrderToUser.Designer.cs
- src/ApiTips.Api/Migrations/20250219071204_MovedAccessTokenFromOrderToUser.cs
- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsAccessService.cs
- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsOrderService.cs
- src/ApiTips.Dal/schemas/data/Order.cs
- src/ApiTips.Dal/schemas/system/User.cs
---
PR составлен по task - DP-1497
> feat!: [DP-1497]  Перенос токена в сущность пользователя

- src/ApiTips.Api/Controllers/AuthController.cs
- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsAccessService.cs
---
PR составлен по task - DP-1563
> feat: [DP-1563] Доработка методов на верификацию и блокировку пользователя

- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsInvoiceService.cs
…рав пользователя на изменение счета
---
PR составлен по task - DP-1587
> feat: [DP-1587] Присвоение статуса по умолчанию для счета, проверка прав пользователя на изменение счета

- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsAccessService.cs
- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsTariffService.cs
---
PR составлен по task - DP-1603
> feat: [DP-1603] Доработка на получение списка тарифов

- proto/api_tips_order/v1/api_tips_order.proto
- src/ApiTips.Api/Extensions/Grpc/GrpcHelper.cs
- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsOrderService.cs
---
PR составлен по task - DP-1615
> feat!: [DP-1615] Доработка метода на создание заказа: в случае запроса от клиента запрос идет по поиску почты из токена, клинап корда

- proto/api_tips_balance/v1/api_tips_balance.proto
- proto/api_tips_invoice/v1/api_tips_invoice.proto
- src/ApiTips.Api/MapperProfiles/Balance/BalanceProfile.cs
- src/ApiTips.Api/MapperProfiles/Invoice/InvoiceProfile.cs
- src/ApiTips.Api/Services/Common/BalanceService.cs
---
PR составлен по task - DP-1624
> feat: [DP-1624] Доработка по отображению истории балансов

- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsOrderService.cs
---
PR составлен по story/task - DP-000/DP-0000
> fix: Добавлена подгрузка счетов

- proto/api_tips_invoice/v1/api_tips_invoice.proto
- src/ApiTips.Api/Models/ServiceModels/InvoiceModel.cs
- src/ApiTips.Api/Services/Common/InvoiceService.cs
- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsInvoiceService.cs
- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsOrderService.cs
---
PR составлен по story DP-1649
> feat: [DP-1649] Доработаны изменения статусов счетов вместе с изменением статусов заказов

- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsBalanceService.cs
---
PR составлен по story/task - DP-1669
> feat: [DP-1669] Правки по списанию всех балансов 

- proto/api_tips_balance/v1/api_tips_balance.proto
- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsBalanceService.cs
---
PR составлен по story/task - DP-918/DP-1702
> feat: [DP-1702] Добавлена возможность получения истории по отдельному пользователю для админки

- proto/api_tips_access/v1/api_tips_access.proto
- src/ApiTips.Api/Services/Grpc/Servers/ApiTipsAccessService.cs
---
PR составлен по story/task - DP-1666/DP-1688
> feat: [DP-1688] Добавлен метод редактирования профиля для пользователя

- src/ApiTips.Api/Services/Common/BalanceService.cs
… при ручном списании
---
PR составлен по task - DP-1653
> feat: [DP-1653] Реализация возможности уходить в отрицательный баланс при ручном списании
